namespace NRuneScape.RuneScape3
{
    public enum Skill
    {
        [Info(17)]
        Agility,
        [Info(1)]
        Attack,
        [Info(23)]
        Construction,
        [Info(8)]
        Cooking,
        [Info(13)]
        Crafting,
        [Info(2)]
        Defence,
        [Info(26)]
        Divination,
        [Info(25)]
        Dungeoneering,
        [Info(20)]
        Farming,
        [Info(12)]
        Firemaking,
        [Info(11)]
        Fishing,
        [Info(10)]
        Fletching,
        [Info(16)]
        Herblore,
        [Info(4)]
        Hitpoints,
        [Info(22)]
        Hunter,
        [Info(27)]
        Invention,
        [Info(7)]
        Magic,
        [Info(15)]
        Mining,
        [Info(6)]
        Prayer,
        [Info(5)]
        Ranged,
        [Info(21)]
        Runecraft,
        [Info(19)]
        Slayer,
        [Info(14)]
        Smithing,
        [Info(3)]
        Strength,
        [Info(24)]
        Summoning,
        [Info(18)]
        Thieving,
        [Info(9)]
        Woodcutting,
        [Info(0)]
        Overall
    }
}
