language: csharp
solution: NRunescape.sln
mono: none
dotnet: 1.0.4
dist: trusty
sudo: required

script:
- dotnet restore
- dotnet build --configuration Release --version-suffix beta-$TRAVIS_BUILDNUMBER
