language: csharp
solution: NRunescape.sln
mono: none
dotnet: 1.0.4
dist: trusty

install:
- dotnet restore

script:
- dotnet migrate
- dotnet build --configuration Release --version-suffix beta-$TRAVIS_BUILDNUMBER
