version: build-{build}
image: Visual Studio 2017
clone_folder: C:\Projects\Discord.Net

configuration: Release

branches:
  only:
    - dev

skip_commits:
  files:
    - docs/*
    - '**/*.html'

pull_requests:
  do_not_increment_build_number: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- ps: $Env:BUILD = "$($Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))"

build_script:
- ps: appveyor-retry dotnet restore NRuneScape.sln
- ps: dotnet build NRuneScape.sln -c "Release" /p:BuildNumber="$Env:BUILD" /p:IsTagBuild=$"Env:APPVEYOR_REPO_TAG"

after_build:
- ps: dotnet pack "src\NRuneScape.Core\NRuneScape.Core.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\NRuneScape.Rest\NRuneScape.Rest.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\NRuneScape.OldSchool\NRuneScape.OldSchool.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\NRuneScape.RuneScape3\NRuneScape.RuneScape3.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: >-
    if ($Env:APPVEYOR_REPO_TAG -eq "true") {
      nuget pack src\NRuneScape\NRuneScape.nuspec -OutputDirectory "artifacts" -properties suffix=""
    } else {
      nuget pack src\NRuneScape\NRuneScape.nuspec -OutputDirectory "artifacts" -properties suffix="-build-$Env:BUILD"
    }
- ps: Get-ChildItem artifacts\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
- ps: dotnet test tests\NRuneScape.RuneScape3.Tests\NRuneScape.RuneScape3.Tests.csproj -c "Release" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet test tests\NRuneScape.OldSchool.Tests\NRuneScape.OldSchool.Tests.csproj -c "Release" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"

deploy:
- provider: NuGet
  server: https://www.myget.org/F/antitcb/api/v2/package
  api_key:
    secure: AWRvUZbGz2G1+FkFE5v/gFjVyKpOW/eldssR+dfg7Yhy6HhCQoAzpFvzyvI/93c1
  symbol_server: https://www.myget.org/F/antitcb/symbols/api/v2/package

- provider: NuGet
  server: https://www.myget.org/F/nrunescape/api/v2/package
  api_key:
    secure: HucCoVE1q+w763JvZXj/czwe5QVkPyslqQ7VFofc20u8uMOCzkRkpsE6WcE2TJlo
  symbol_server: https://www.myget.org/F/nrunescape/symbols/api/v2/package

notifications:
- provider: Webhook
  url: 
    secure: 57BGR6qgxNvqyo4szSetG8DX0JtWn6Whx+lib2TCYQF1p2oiO/dzz41Yls7Pts7waZ5d5UwpekMLFXpugn45G+4G8wLbDYKzNihVLJu6hCsABPMKCcoNLjHsGSGL5TI7Mbb8arOcCei4FFSLQfPJE98v8pw6/4AhbbuRxlMS1jk=
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true