version: beta-{build}
image: Visual Studio 2017
clone_folder: C:\Projects\Discord.Net

configuration: Release

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- ps: $Env:BUILD = "$($Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))"

build_script:
- ps: appveyor-retry dotnet restore NRuneScape.sln
- ps: dotnet build NRuneScape.sln -c "Release" /p:BuildNumber="$Env:BUILD" /p:IsTagBuild=$"Env:APPVEYOR_REPO_TAG"

after_build:
- ps: dotnet pack "src\NRuneScape.Core\NRuneScape.Core.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\NRuneScape.Rest\NRuneScape.Rest.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\NRuneScape.OldSchool\NRuneScape.OldSchool.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\NRuneScape.RuneScape3\NRuneScape.RuneScape3.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: >-
    if ($Env:APPVEYOR_REPO_TAG -eq "true") {
      nuget pack src\NRuneScape\NRuneScape.nuspec -OutputDirectory "artifacts" -properties suffix=""
    } else {
      nuget pack src\NRuneScape\NRuneScape.nuspec -OutputDirectory "artifacts" -properties suffix="-build-$Env:BUILD"
    }
- ps: Get-ChildItem artifacts\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
- ps: dotnet test tests\NRuneScape.RuneScape3.Tests\NRuneScape.RuneScape3.Tests.csproj -c "Release" --no-build /:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet test tests\NRuneScape.OldSchool.Tests\NRuneScape.OldSchool.Tests.csproj -c "Release" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
